### ISSUE TITLE
really great work; putting it to use

### ISSUE THREAD

**Issue by timelyportfolio** [annaghi/d3.chart.layout.hierarchy#1]
Really great work!  Thanks.  I just wanted to let you know that I am putting `d3.chart.layout` to good use in a R htmlwidget [`networkD3`](https://github.com/christophergandrud/networkD3).  I hope to be able to fully test it and if possible offer some pulls to `d3.chart.layout` for additional functionality and bug fixes.  Thanks again.

**Comment by bansaghi** [comment]
Thanks, I am glad to hear that. Please, feel free to enhance these charts.

I tend to impove the overall layout using the [d3.chart.base](https://github.com/iros/d3.chart.base), and add the new `width` and `height` attributes accordingly in this year.
